default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: ieupxqw5
  host: localhost
  port: 5433
  timeout: 5000

development:
  <<: *default
  database: apitask
test:
  <<: *default
  database: apitask

production:
  <<: *default
  database: apitask
